version: '3.8'

services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUBDOMAINS=musicapp-devops
      - TOKEN=${DUCKDNS_TOKEN}
    restart: always

  gateway:
    image: lscr.io/linuxserver/swag:latest
    container_name: gateway
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=${DUCKDNS_DOMAIN}
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
    volumes:
      - ./gateway-config:/config
    ports:
      - 443:443
      - 80:80
    restart: always
    networks:
      - app-network
    depends_on:
      - client
      - api

  api:
    image: ghcr.io/odrymark/musicapp/api:latest
    build:
      context: ./server
      dockerfile: Api/Dockerfile
    depends_on:
      featurehub:
        condition: service_started
    networks:
      - app-network
    expose:
      - 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${CONNECTIONSTRINGS__DEFAULTCONNECTION}
      - Jwt__Key=${JWT__KEY}
      - Jwt__Issuer=${JWT__ISSUER}
      - Jwt__Audience=${JWT__AUDIENCE}
      - Jwt__ExpireMinutes=${JWT__EXPIREMINUTES}
      - RefreshToken__ExpireDays=${REFRESHTOKEN__EXPIREDAYS}
      - R2__AccessKey=${R2__ACCESSKEY}
      - R2__SecretKey=${R2__SECRETKEY}
      - R2__BucketName=${R2__BUCKETNAME}
      - R2__Endpoint=${R2__ENDPOINT}
      - FeatureHub__Url=${FEATUREHUB__URL}
      - FeatureHub__SdkKey=${FEATUREHUB__SDKKEY}
    restart: always

  client:
    image: ghcr.io/odrymark/musicapp/client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - app-network
    expose:
      - 5173
    depends_on:
      - api
    restart: always

  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - ./server/featurehub:/db
    networks:
      - app-network
    environment:
      - PORT=8085

networks:
  app-network:
    driver: bridge
